version: "3.8"

services: 
  server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
      - discord_bot
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    env_file:
      - ./src/env/mysql.env
    volumes:
      - data:/var/lib/mysql
  discord_bot:
    build:
      context: ./
      dockerfile: ./dockerfiles/discord_bot.dockerfile
    restart: always
    volumes:
      - ./discord_bot:/app
      - /app/node_modules
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
volumes:
  data: